#include <QVector>
#include <QMap>
#include <QSet>
#include <QPair>
#include "types.h"

GrammarSymbol sym_end("$END", SYMBOL_END);
GrammarSymbol sym_13("TERM", "\"[^\"\n\r \t]+\"", SYMBOL_TERMINAL);
GrammarSymbol sym_10("NTERM", "[A-Z0-9][A-Z0-9]*", SYMBOL_TERMINAL);
GrammarSymbol sym_18("EQ", "=", SYMBOL_TERMINAL);
GrammarSymbol sym_5("BREAK", ";", SYMBOL_TERMINAL);
GrammarSymbol sym_2("programm", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_17("OR", "\\|", SYMBOL_TERMINAL);
GrammarSymbol sym_0("$ACCEPT", SYMBOL_START);
GrammarSymbol sym_8("axiom", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_3("non-terms", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_11("terms", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_6("rules", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_7("rule", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_4("non-terms-list", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_14("terms-list", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_16("right-part", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_15("rule-part", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_12("term-or-non-term", SYMBOL_NON_TERMINAL);
GrammarSymbol sym_9("AXIOM_KW", "\\$AXIOM", SYMBOL_TERMINAL);

QSet<GrammarSymbol*> terms = {
	&sym_17, &sym_10, &sym_5, &sym_13, &sym_18, &sym_9,
};

QVector<QPair<GrammarSymbol*, QVector<GrammarSymbol*>>> prods = {
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_0, {
		&sym_2,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_3, {
		&sym_4, &sym_5,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_6, {
		&sym_7,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_6, {
		&sym_7, &sym_6,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_8, {
		&sym_9, &sym_10, &sym_5,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_2, {
		&sym_8, &sym_3, &sym_11, &sym_6,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_12, {
		&sym_13,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_12, {
		&sym_10,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_14, {
		&sym_13,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_14, {
		&sym_13, &sym_14,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_15, {
		&sym_12,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_15, {
		&sym_12, &sym_15,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_4, {
		&sym_10,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_4, {
		&sym_10, &sym_4,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_16, {
		&sym_15,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_16, {
		&sym_15, &sym_17, &sym_16,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_11, {
		&sym_14, &sym_5,
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&sym_7, {
		&sym_10, &sym_18, &sym_16, &sym_5,
	}),
};

QVector<QMap<GrammarSymbol*, QPair<GrammarAction, int>>> action = {
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_SHIFT, 1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_SHIFT, 4)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_SHIFT, 5)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_ACCEPT, 0)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_SHIFT, 8)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_SHIFT, 5)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_REDUCE, 12)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_SHIFT, 10)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_SHIFT, 13)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_REDUCE, 4)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_REDUCE, 13)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_SHIFT, 10)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_REDUCE, 8)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_SHIFT, 15)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_SHIFT, 16)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_REDUCE, 1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_REDUCE, 9)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_REDUCE, 16)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_SHIFT, 19)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_REDUCE, 5)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_REDUCE, 2)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_SHIFT, 16)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_SHIFT, 22)},
		{&sym_10, QPair<GrammarAction, int>(ACT_SHIFT, 21)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_REDUCE, 3)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_REDUCE, 7)},
		{&sym_10, QPair<GrammarAction, int>(ACT_REDUCE, 7)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_REDUCE, 7)},
		{&sym_17, QPair<GrammarAction, int>(ACT_REDUCE, 7)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_REDUCE, 6)},
		{&sym_10, QPair<GrammarAction, int>(ACT_REDUCE, 6)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_REDUCE, 6)},
		{&sym_17, QPair<GrammarAction, int>(ACT_REDUCE, 6)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_SHIFT, 22)},
		{&sym_10, QPair<GrammarAction, int>(ACT_SHIFT, 21)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_REDUCE, 10)},
		{&sym_17, QPair<GrammarAction, int>(ACT_REDUCE, 10)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_REDUCE, 14)},
		{&sym_17, QPair<GrammarAction, int>(ACT_SHIFT, 27)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_SHIFT, 28)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_REDUCE, 11)},
		{&sym_17, QPair<GrammarAction, int>(ACT_REDUCE, 11)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_SHIFT, 22)},
		{&sym_10, QPair<GrammarAction, int>(ACT_SHIFT, 21)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_REDUCE, 17)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_REDUCE, 17)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&sym_end, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_5, QPair<GrammarAction, int>(ACT_REDUCE, 15)},
		{&sym_17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&sym_9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
};

QVector<QMap<GrammarSymbol*, int>> _goto = {
	{
		{&sym_2, 3},
		{&sym_8, 2},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, 6},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, 7},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, 9},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, 12},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, 11},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, 14},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, 17},
		{&sym_7, 18},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, 20},
		{&sym_7, 18},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, 25},
		{&sym_15, 24},
		{&sym_12, 23},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, 26},
		{&sym_12, 23},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, 29},
		{&sym_15, 24},
		{&sym_12, 23},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
	{
		{&sym_2, -1},
		{&sym_8, -1},
		{&sym_3, -1},
		{&sym_11, -1},
		{&sym_6, -1},
		{&sym_7, -1},
		{&sym_4, -1},
		{&sym_14, -1},
		{&sym_16, -1},
		{&sym_15, -1},
		{&sym_12, -1},
	},
};

