#include "grammar_main.h"

GrammarSymbol s1("$END", SYMBOL_END);
GrammarSymbol s13("TERM", "\"[^\"\n\r \t]+\"", SYMBOL_TERMINAL);
GrammarSymbol s10("NTERM", "[A-Z0-9][A-Z0-9]*", SYMBOL_TERMINAL);
GrammarSymbol s18("EQ", "=", SYMBOL_TERMINAL);
GrammarSymbol s5("BREAK", ";", SYMBOL_TERMINAL);
GrammarSymbol s2("programm", SYMBOL_NON_TERMINAL);
GrammarSymbol s17("OR", "\\|", SYMBOL_TERMINAL);
GrammarSymbol s0("$ACCEPT", SYMBOL_START);
GrammarSymbol s8("axiom", SYMBOL_NON_TERMINAL);
GrammarSymbol s3("non-terms", SYMBOL_NON_TERMINAL);
GrammarSymbol s11("terms", SYMBOL_NON_TERMINAL);
GrammarSymbol s6("rules", SYMBOL_NON_TERMINAL);
GrammarSymbol s7("rule", SYMBOL_NON_TERMINAL);
GrammarSymbol s4("non-terms-list", SYMBOL_NON_TERMINAL);
GrammarSymbol s14("terms-list", SYMBOL_NON_TERMINAL);
GrammarSymbol s16("right-part", SYMBOL_NON_TERMINAL);
GrammarSymbol s15("rule-part", SYMBOL_NON_TERMINAL);
GrammarSymbol s12("term-or-non-term", SYMBOL_NON_TERMINAL);
GrammarSymbol s9("AXIOM_KW", "\\$AXIOM", SYMBOL_TERMINAL);

QSet<GrammarSymbol*> terms = {
	&s17, &s10, &s5, &s13, &s18, &s9, 
};
QVector<QPair<GrammarSymbol*, QVector<GrammarSymbol*>>> prods = {
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s0, {
		&s2, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s3, {
		&s4, &s5, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s6, {
		&s7, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s6, {
		&s7, &s6, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s8, {
		&s9, &s10, &s5, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s2, {
		&s8, &s3, &s11, &s6, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s12, {
		&s13, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s12, {
		&s10, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s14, {
		&s13, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s14, {
		&s13, &s14, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s15, {
		&s12, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s15, {
		&s12, &s15, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s4, {
		&s10, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s4, {
		&s10, &s4, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s16, {
		&s15, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s16, {
		&s15, &s17, &s16, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s11, {
		&s14, &s5, 
	}),
	QPair<GrammarSymbol*, QVector<GrammarSymbol*>>(&s7, {
		&s10, &s18, &s16, &s5, 
	}),
};

QVector<QMap<GrammarSymbol*, QPair<GrammarAction, int>>> action = {
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_SHIFT, 1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_SHIFT, 4)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_SHIFT, 5)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_ACCEPT, 0)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_SHIFT, 8)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_SHIFT, 5)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_REDUCE, 12)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_SHIFT, 10)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_SHIFT, 13)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_REDUCE, 4)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_REDUCE, 13)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_SHIFT, 10)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_REDUCE, 8)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_SHIFT, 15)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_SHIFT, 16)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_REDUCE, 1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_REDUCE, 9)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_REDUCE, 16)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_SHIFT, 19)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_REDUCE, 5)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_REDUCE, 2)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_SHIFT, 16)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_SHIFT, 22)},
		{&s10, QPair<GrammarAction, int>(ACT_SHIFT, 21)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_REDUCE, 3)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_REDUCE, 7)},
		{&s10, QPair<GrammarAction, int>(ACT_REDUCE, 7)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_REDUCE, 7)},
		{&s17, QPair<GrammarAction, int>(ACT_REDUCE, 7)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_REDUCE, 6)},
		{&s10, QPair<GrammarAction, int>(ACT_REDUCE, 6)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_REDUCE, 6)},
		{&s17, QPair<GrammarAction, int>(ACT_REDUCE, 6)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_SHIFT, 22)},
		{&s10, QPair<GrammarAction, int>(ACT_SHIFT, 21)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_REDUCE, 10)},
		{&s17, QPair<GrammarAction, int>(ACT_REDUCE, 10)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_REDUCE, 14)},
		{&s17, QPair<GrammarAction, int>(ACT_SHIFT, 27)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_SHIFT, 28)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_REDUCE, 11)},
		{&s17, QPair<GrammarAction, int>(ACT_REDUCE, 11)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_SHIFT, 22)},
		{&s10, QPair<GrammarAction, int>(ACT_SHIFT, 21)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_REDUCE, 17)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_REDUCE, 17)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
	{
		{&s1, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s13, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s10, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s18, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s5, QPair<GrammarAction, int>(ACT_REDUCE, 15)},
		{&s17, QPair<GrammarAction, int>(ACT_NONE, -1)},
		{&s9, QPair<GrammarAction, int>(ACT_NONE, -1)},
	},
};

QVector<QMap<GrammarSymbol*, int>> _goto = {
	{
		{&s2, 3},
		{&s8, 2},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, 6},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, 7},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, 9},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, 12},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, 11},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, 14},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, 17},
		{&s7, 18},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, 20},
		{&s7, 18},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, 25},
		{&s15, 24},
		{&s12, 23},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, 26},
		{&s12, 23},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, 29},
		{&s15, 24},
		{&s12, 23},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
	{
		{&s2, -1},
		{&s8, -1},
		{&s3, -1},
		{&s11, -1},
		{&s6, -1},
		{&s7, -1},
		{&s4, -1},
		{&s14, -1},
		{&s16, -1},
		{&s15, -1},
		{&s12, -1},
	},
};

